## Palindrome

In [ ]:
chaine = input("Entrez un mot :")
if chaine == chaine[::-1]:
    print (chaine, "est un palindrome")
else:
    print (chaine, "n'est pas un palindrome")

## Lancer de dés

In [2]:
from random import* 

# On tire 5 nombres aléatoire entre 1 et 6
de1=randint(1,6)
print(de1)

de2=randint(1,6)
print(de2)

de3=randint(1,6)
print(de3)

de4=randint(1,6)
print(de4)

de5=randint(1,6)
print(de5)
     
sommeDes = de1 + de2 + de3 + de4 + de5
print(sommeDes)

2
1
6
2
6
17


## Calcul des moyennes

In [ ]:
sommeNotes = 0
moyenne = 0
for i in range(5):
    note = int(input("Entrez une note :"))
    sommeNotes += note # somme des notes
    print(sommeNotes)    
moyenne = sommeNotes / 5 # moyenne issue de la des notes
print(moyenne)

## Traitement des données contenues dans une matrice

4.1

In [41]:
tab2d = [[6, 2, 3, 5], [4, 6, 2, 6]]
impairsI = []
impairsJ = []
a=()
def nbImpair():
    a%2 !=0
for i in tab2d:
    j=0
    if i == nbImpair:
        impairsI.append(i)
        i+=1
    print(impairsI)
    for j in tab2d:
        if j == nbImpair:
            impairsJ.append(j)
            j+=1
            print(impairsJ)
sommeImpairs = impairsI + impairsJ
print(sommeImpairs)

[]
[]
[]


4.2

In [10]:
import numpy as np
tab2d = np.array([[6, 2, 3, 5], [4, 6, 2, 6], [1, 3, 6, 7], [3, 6, 3, 8]])
print(tab2d) # Test
print(np.diag(tab2d)) # 1ère diagonale
print(np.diag(tab2d[::-1])) # 2ème diagonale

[[6 2 3 5]
 [4 6 2 6]
 [1 3 6 7]
 [3 6 3 8]]
[6 6 6 8]
[3 3 2 5]


4.3

In [7]:
import numpy as np
tab2d = np.array([[6, 2, 3, 5], [4, 6, 2, 6], [1, 3, 6, 7], [3, 6, 3, 8]])
def verification():
    a = np.sum([np.diag(tab2d)])
    b = np.sum([np.diag(tab2d[::1])])
    if a == b:
        print("Oui")
    else:
        print("Non")

4.4

In [5]:
import numpy as np
tab = np.array([[6, 2, 3, 5], [4, 4, 2, 6], [1, 3, 6, 7], [3, 6, 3, 8],[6, 0, 1, 4]])
print(tab)

a = (tab.sum(axis=1)) / 4 # moyennes par colonnes
print(a)

b = np.argmax(a) # indice de la colonne à la moyenne la plus forte
print(b)

[[6 2 3 5]
 [4 4 2 6]
 [1 3 6 7]
 [3 6 3 8]
 [6 0 1 4]]
[4.   4.   4.25 5.   2.75]
3


## Base de données étudiante

5.1

In [2]:
import numpy as np
bddEtudiants = np.array([['Numéro', 'Nom', 'Prénom'], [1, 'Yborra', 'Amandine'], [2, 'Ben Khalaf', 'Haïfa'], [3, 'Durand', 'Matthieu'], [4, 'Dumanois', 'Axel']])
print(bddEtudiants)

[['Numéro' 'Nom' 'Prénom']
 ['1' 'Yborra' 'Amandine']
 ['2' 'Ben Khalaf' 'Haïfa']
 ['3' 'Durand' 'Matthieu']
 ['4' 'Dumanois' 'Axel']]


5.2

## Année bissextile

In [4]:
annee = int(input("Saisissez une année : "))

if annee % 400 == 0 or (annee % 4 == 0 and annee % 100 != 0):
    print("L'année est bissextile.")
else:
    print("L'année saisie n'est pas bissextile.")

Saisissez une année : 2008
L'année est bissextile.


## Echange de triangles

In [1]:
import numpy as np
tab = np.array([[10, 11, 45, 78],[23, 44, 12, 56],[56, 90, 67, 89],[47, 78, 55, 34]])
np.transpose(tab)

array([[10, 23, 56, 47],
       [11, 44, 90, 78],
       [45, 12, 67, 55],
       [78, 56, 89, 34]])

## Fibonnacci

In [ ]:
n = int(input("Tapez un nombre :"))
def fib(n):
    if n==1 or n==2:
        return 1
    else:   
        return fib(n-1)+fib(n-2)
print (fib(n))